### ISSUE TITLE
[alien,schur]

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#1010]
Hello,
If Eigen3 is found TestSchur.cc build fails: 

framework/alien/standalone/src/refsemantic/tests/TestSchur.cc:308:10: error: ‘SchurOp’ is not a member of ‘Alien’
  308 |   Alien::SchurOp op(A, b);
      |          ^~~~~~~
framework/alien/standalone/src/refsemantic/tests/TestSchur.cc:323:18: error: ‘op’ was not declared in this scope
  323 |     auto error = op.computePrimarySystem(pA, pb);
      |                  ^~
Arcane/framework/alien/standalone/src/refsemantic/tests/TestSchur.cc:345:18: error: ‘op’ was not declared in this scope
  345 |     auto error = op.computePrimarySystem(pA, pb);
      |                  ^~

A+
Thomas

**Comment by grospelliergilles** [comment]
I think @stdcm has fixed the bug in #1005

**Comment by stdcm** [comment]
Indeed. I will merge today.

**Comment by stdcm** [comment]
Resolved by #1005
