### ISSUE TITLE
FindZoltan.cmake does not allow  Zoltan2_DIR

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#1011]
Hello,
In arcane/cmake/Modules/FindZoltan.cmake there is the line:
find_package(Zoltan2 NO_MODULE QUIET)
The NO MODULE option does not allow the use of Zoltan2_DIR to find package config. Why this choice ?
I recommend to remove NO_MODULE option.

A+
Thomas

**Comment by grospelliergilles** [comment]
I do not remember about this choice.
I will try to remove NO_MODULE option and see if it works
