### ISSUE TITLE
`Filterer::apply` with a predicate

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#1023]
In addition to the original prototype of `Filterer::apply(..., SmallSpan<const FlagType> flags)`, is it possible to have an additional signature:
```c++
template<Predicate>
void apply(RunQueue*queue, SmallSpan< const DataType > input, SmallSpan< DataType > output, Predicate pred)
```

This predicate should have the attribute `ARCCORE_HOST_DEVICE`.

Example:
```c++
SmallSpan<const Real> in_values(values.data(), values.size());

auto pred = [=] ARCCORE_HOST_DEVICE (Integer i)
{
  return (in_values[i]<0.);
};

filterer.apply(queue, input, output, pred);
```

**Comment by DavidDureau** [comment]
It seems there is a problem with `applyIf` with the Sequential policy and the CUDA policy.

The `select_lambda` method is called on the `input[i]` value but not directly on the index `i`.

A fix for the Sequential policy should be:
```c++
diff --git a/arcane/src/arcane/accelerator/Filter.h b/arcane/src/arcane/accelerator/Filter.h
index cc17af06b..8616e0f84 100644
--- a/arcane/src/arcane/accelerator/Filter.h
+++ b/arcane/src/arcane/accelerator/Filter.h
@@ -218,7 +218,7 @@ class GenericFilteringIf
     case eExecutionPolicy::Sequential: {
       Int32 index = 0;
       for (Int32 i = 0; i < nb_item; ++i) {
-        if (select_lambda(input[i])) {
+        if (select_lambda(i)) {
           output[index] = input[i];
           ++index;
         }
```

I don't know how to fix the bug for the CUDA policy.

In addition, is it possible to have a multi-thread implementation of `apply` and `applyIf`?

**Comment by grospelliergilles** [comment]
What you want is not possible in CUDA or ROCM. The predicate works on the value and not on the index. You can see an example of `::cub::DeviceSelect::If` here: https://nvlabs.github.io/cub/structcub_1_1_device_select.html

**Comment by DavidDureau** [comment]
Ah I understand but we need to select on a predicate where the condition doesn't depend on the input array (in fact, we need to replace the condition  `flag[i]` by `select_lambda(i)` like asked in the initial issue).

I have an implementation in a small program using a succession of `stdpar` functions, maybe we can adapt it by using `cub` functions?

**Comment by grospelliergilles** [comment]
Yes you can send it and I will take a look at it. Thanks.

**Comment by grospelliergilles** [comment]
PR #1210 add the functionality you want
