### ISSUE TITLE
Using a view of  `MeshPartialVariableScalarRefT` into an accelerator loop

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#1275]
Is it possible to have something like this?

```c++
void compute(CellGroup part_group, 
    const PartialVariableCellReal& part1, 
    PartialVariableCellReal& part2, 
    PartialVariableCellReal& part3)
{
  auto command = ... ;

  auto in_part1 = ax::viewIn(command, part1);
  auto out_part2 = ax::viewOut(command, part2);
  auto inout_part3 = ax::viewInOut(command, part3);

  command << RUNCOMMAND_ENUMERATE(Cell, cid, part_group)
  {
    out_part2[cid] = 2*in_part1[cid];
    inout_part3[cid] += in_part1[cid];
  };
}
```

**Comment by grospelliergilles** [comment]
I have questions about your issue:
- are `part1`, `part2` and `part3` partial variables on the same group which is `part_group` ?
- do you want to access normal variables in your loop ?

**Comment by DavidDureau** [comment]
In the few examples I saw, `part1`, `part2` and `part3` seems to have the same support.

Or maybe, `part_group` would just be included into the intersection of the `part`i`.itemGroup()`.

And for your second question, yes we can access normal variables in my loop.

**Comment by grospelliergilles** [comment]
Thanks for the answer.
So there is no need for indexing with hash table in that case.
I have added a way to obtain iterator index in #1270. I will add a way to use this index in partial variable.
