### ISSUE TITLE
Define accelerator API for cartesian loops per direction

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#130]
1. Identify patterns for cartesian loops : 

- processing with a stencil (greater than or equal to 1) per direction, 
- AMR patch-based, 
- address multi-environment variables in cartesian loop, 
- ...

2. define the API to address accelerator (GPU, ...)
3. implementation : take care of performances

**Comment by DavidDureau** [comment]
Is it possible to hide the mesh connectivity implementation with performance efficiency?

- connectivity on unstructured mesh;
- or connectivity by computing local ids on cartesian mesh (or on a cartesian patch).

**Comment by DavidDureau** [comment]
To go faster, in the first time, we could add the `ARCCORE_HOST_DEVICE` attribute to `{Cell|Face|Node}DirectionMng` methods' and the other cartesian classes.

In consequence, we only would make a cartesian view upon the unstructured mesh in the first time.

In the second time, we could see how to hide a real cartesian mesh or an unstructured mesh.

**Comment by DavidDureau** [comment]
So, do you think it would be easier to use `Cart{Cell|Face|Node}DirectionMng` classes implemented in MaHyCo/Pattern4GPU?
These classes have `ARCCORE_HOST_DEVICE` attributes and uses `{Cell|Face|Node}LocalId`.

https://github.com/cea-hpc/MaHyCo/blob/75bfe5e5fc5417961456cfa02ce3c15220a551ec/src/cartesian/CartCellDirectionMng.h
https://github.com/cea-hpc/MaHyCo/tree/Mahyco_gpu2/src/cartesian

These classes are really close to the Arcane cartesian views.
We can find numerous examples here:
https://github.com/cea-hpc/pattern4gpu/blob/f9aa1b7a3dbfb4cfd7cd706aeb6a1a95fba44f43/src/Pattern4GPUTestCartesian.cc#L475

However, these classes make the assumption that the mesh is truly cartesian without patch.

**Comment by grospelliergilles** [comment]
Thanks for the information. I will look at that.

**Comment by grospelliergilles** [comment]
First implementation will be available after #474
