### ISSUE TITLE
Spack recipe for accelerator support

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#132]
To be able to install Arcane configured with the accelerator API support (CUDA in the first time).

We need two compilers:

1. one for the main part of Arcane which doesn't depend on accelerator. This compiler could be `gcc`;
2. the other to compile the accelerator part. This compiler could be `nvcc` from `nvhpc/21.9`.

**Comment by cedricchevalier19** [comment]
Fixed by arcaneframework/spack_recipes#14
