### ISSUE TITLE
Using a pool to create RunQueue with the greatestPriority

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#160]
A call to `cudaStreamCreateWithPriority` seems to be costly.

Like for queues with default priority, is it possible to create a pool of `RunQueueImpl` instances with the greatest priority (negative value)?

In https://github.com/arcaneframework/framework/blob/main/arcane/src/arcane/accelerator/core/Runner.cc , in method `Runner::_internalCreateOrGetRunQueueImpl(const RunQueueBuildInfo& bi)`, something like:
```
impl::RunQueueImpl* Runner::
_internalCreateOrGetRunQueueImpl(const RunQueueBuildInfo& bi)
{
  _checkIsInit();
  // Si on utilise les paramètres par défaut ou avec la priorité la plus haute, on peut utilier une RunQueueImpl
  // issue du pool.
  eExecutionPolicy p = executionPolicy();
  if (bi.isDefault())
    return _internalCreateOrGetRunQueueImpl(p);
  else if (bi.isGreatest())
    return _internalCreateOrGetRunQueueImplGreatest(p);
  impl::IRunQueueRuntime* runtime = _getRuntime(p);
  ARCANE_CHECK_POINTER(runtime);
  auto* queue = new impl::RunQueueImpl(this,0,runtime,bi);
  return queue;
}
```

**Comment by grospelliergilles** [comment]
Yes I think it is possible to do that.

**Comment by DavidDureau** [comment]
Hi, do you know RMM?
https://github.com/rapidsai/rmm
May be, it could be more efficient to manage pool of streams or memory allocations ...

**Comment by grospelliergilles** [comment]
Thanks for the link. I do not known this library but it is planned to use LLNL/Umpire (#112) which seems similar.

**Comment by francois-letierce** [comment]
We propose a 1st implementation of this feature via the accelerator/AsyncRunQueuePool class (which was design by D. Dureau in Pattern4GPU), usable since commit fbba33deeffa6b5de7144cf5e0791b12daf213a5
