### ISSUE TITLE
`mpDelete` function ?

### ISSUE THREAD

**Issue by cedricchevalier19** [arcaneframework/framework#166]
It is currently possible to create new `IMessagePassingMng` with `StandaloneMpiMessagePassingMng()` or `mpSplit()` however it is not clear how user can delete these objects.

Currently in Alien we use `delete` but it can be an issue if Arccore switch from `new` to another memory management function.

**Comment by grospelliergilles** [comment]
I agree we need to improve how to manage the lifetime of this class.
`IMessagePassingMng` should be reference counted like `IParallelMng`
