### ISSUE TITLE
Replace the pattern {EnvCellVectorView => CellVector => MatCellVector => MatCellVectorView}

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#1676]
This pattern is often used to build a subset of a MatCellVectorView from an EnvCellVectorView depending on a criteria/predicate.

But this pattern is not GPU-compliant: it implies memory allocation and serial list construction on CPU and at the end memory transfers (H<->D).

Is it possible to have a GPU-compliant way to build this subset?

**Comment by grospelliergilles** [comment]
Yes it should be possible. I will look at samples of this pattern and optimize them for accelerators

**Comment by DavidDureau** [comment]
Yes, of course, I can show you an example.
