### ISSUE TITLE
ComponentCell::globalCellId() on accelerator

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#1712]
Is it possible to get the CellLocalId of the global cell of a CompentCell?

Something like that:
```C++
ARCCORE_HOST_DEVICE Int32 ComponentCell::globalCellId() const
```
The return type could be a CellLocalId.

**Comment by grospelliergilles** [comment]
Yes I will add this.
The method `ComponentCell::globalCellLocalId()` already exists but is not yes accessible on accelerator.
