### ISSUE TITLE
No released versions of Arccore can be compiled on Ubuntu 20.04

### ISSUE THREAD

**Issue by cedricchevalier19** [arcaneframework/framework#255]
Fix is available on `main` branch since #208 but no correctly tagged released has been done for Arccore yet.

For [Alien](https://github.com/arcaneframework/alien), we have decided to remove copies of Arccon and Arccore from the source tree. And for quality reasons, we want to used properly flagged releases of Arccore and Arccon.

This issue is strongly related to #244.

**Comment by cedricchevalier19** [comment]
Yes, sorry for the typo. I fix the title of the PR.

**Comment by grospelliergilles** [comment]
Ok. Thanks to @AlexlHer and PR #253 merged yesterday we now have a CI on ubuntu 22.04 so we can do a tarball which can pass all the tests on this distribution.

I will check everything is OK on our applications and do a tarball before the end of the week.

**Comment by cedricchevalier19** [comment]
Ok, thanks a lot.

**Comment by grospelliergilles** [comment]
I have done a release for Arccore:

https://github.com/arcaneframework/framework/releases/tag/arccore-v2.0.11.0

Tell me if it works for you

**Comment by cedricchevalier19** [comment]
Ok for me.

Thanks.
