### ISSUE TITLE
Perfomance issue on a kernel using `Arcane::Accelerator::ReducerMin`

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#350]
In the MaHyCo code, one kernel (`computeHydroDeltaT`) has to perform a min reduction
https://github.com/cea-hpc/MaHyCo/blob/f0ecc2d986910aa188f436bcefa01d1f52b0d1c4/src/MahycoModule.cc#L2073

Periodically (~ every 50 iterations), the time spent in this kernel dramatically increases and has an important impact on the total time step.
Here is the elapsed time per cycle:
![KernelReduceElpsTm](https://user-images.githubusercontent.com/78317669/191689089-4080b88f-923c-4c0c-b656-1b614aac5ca4.png)

Here is the nsys trace for around 200 iterations, we can see a "wave" of 3 `cudaStreamSynchronize`:
![KernelReduce1](https://user-images.githubusercontent.com/78317669/191689691-2eec204c-e9d5-47ba-b24d-0a1bc849bb98.png)

And a zoom on 2 iterations, on the left a regular iteration where the time spent in `computeDeltaT` is low, and on the right an iteration where the time spent in `computeDeltaT` is multiplied by ~60.
![KernelReduce2a](https://user-images.githubusercontent.com/78317669/191692993-7920bd0d-9c16-46be-b1ce-cc43f4ba9c24.png)
![KernelReduce2](https://user-images.githubusercontent.com/78317669/191693774-50c7dc80-92f9-43c2-86d9-c88a2bed3eec.png)

Could you help me?

**Comment by grospelliergilles** [comment]
This is very strange. I will look at that.
At the moment the class 'Reduce' is not optimized on the grid. It uses `atomicMin/Max/Add` outside of a bloc. This may explains the behavior.
If you send me the datafile used for this bench I will look the problem.

**Comment by DavidDureau** [comment]
In the case of `-A,AcceleratorRuntime=cuda`, why don't use `CUB` to implement your reduction?

**Comment by grospelliergilles** [comment]
`cub` can not be used inside a loop. We have to create a temporary array and do the reduction on that array.

But it may be interesting to have such a method for specific cases or when we want to do performance comparison between `Arcane::Reducer` and `cub` optimized algorithms.

**Comment by DavidDureau** [comment]
It seems you can perform a partial reduction on a block inside a kernel:
https://nvlabs.github.io/cub/classcub_1_1_block_reduce.html

An example written by C. Augonnet (change the `.txt` extension into `.cu`):
[pi_redux.txt](https://github.com/arcaneframework/framework/files/9643883/pi_redux.txt)

**Comment by grospelliergilles** [comment]
I tried to reproduce your problem on my laptop without success.
I will try on inti.
I have implemented another reduce mechanism using grid reduction (#365 and #379). Il will also try these algorithms.

**Comment by grospelliergilles** [comment]
PR #381 should resolve your issue.
