### ISSUE TITLE
Add `-G` and more to compilation flags for CUDA files in Debug mode

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#412]
In order to use Nvidia tools (like compute-sanitizer) or a debugger, the CUDA files need to be compiled with the following flags:
```
Compile : nvcc -g -G foo.cu -o foo or nvcc -Xcompiler -rdynamic -lineinfo -o foo foo.cu
-G: To generate debug info for CUDA app – slow
-lineinfo: Generate line number information
-rdynamic: The host compiler retains function symbols
-Xcompiler: To specify flags to the host compiler
```

Is it possible to add this flags optionally?

**Comment by grospelliergilles** [comment]
The option `-lineinfo` is always used with Arcane.
You can add any compiler flag using `CMAKE_CUDA_FLAGS` in the configuration step:

~~~
cmake -S ... -B ... -DCMAKE_CUDA_FLAGS=-G
~~~

Do you need something more ?

**Comment by DavidDureau** [comment]
It could be sufficient.

However, when I configure the project with `-DCMAKE_CUDA_FLAGS=-G`, I have the following message:
```
nvcc warning : '--device-debug (-G)' overrides '--generate-line-info (-lineinfo)
ptxas warning : Conflicting options --device-debug and --generate-line-info specified, ignoring --generate-line-info option
```

**Comment by grospelliergilles** [comment]
Yes I have the same warning.
It should still work.
If you only need `-rdynamic -lineinfo` maybe I can always add them to the command line if they do not impact performance.

**Comment by DavidDureau** [comment]
If it is in the case of debugging mode, performance is not the key point so maybe we could be add these flags.

Or, maybe it exists a CMAKE variable to add flags the host compiler?

**Comment by grospelliergilles** [comment]
You can do the following: `CMAKE_CUDA_FLAGS=-Xcompiler ...` to add flags to the host

**Comment by grospelliergilles** [comment]
I will add a CMake configuration option `ARCANE_CUDA_DEVICE_DEBUG` to automatically add the `--device-debug` option.
