### ISSUE TITLE
improve quality code, framework

### ISSUE THREAD

**Issue by roottreej** [arcaneframework/framework#519]
I detected some default on code about quality stuff.      
These are detected today on main branch of framework.    
Just to improve it, here I put some of them.    

| file             |   line | default   |
| -------------- | ------- | -------- |
| framework-main/arcane/src/arcane/core/DomLibXml2.cc | 4293 | parenthese error |
| framework-main/arcane/src/arcane/impl/ParallelReplication.cc | 21 | bracket error |
| framework-main/arccore/src/message_passing_mpi/arccore/message_passing_mpi/MpiSerializeMessageList.cc | 135 | condition always false |
| framework-main/arcane/src/arcane/tests/TaskUnitTest.cc |540 | variable "sum" uninitialized |
| framework-main/arcane/src/arcane/tests/TaskUnitTest.cc |574 | variables "x" and "y" uninitialized |
| framework-main/arcane/extras/Simd/bench/SimdHydroBench.cc | all | ISO-8859 text |
| framework-main/arcane/extras/Simd/bench/NoVecHydroBench.cc |all | ISO-8859 text |
| framework-main/arcane/ceapart/src/arcane/geometric/GeneratedGeomShapeViewDeclarations.h |all |  ISO-8859 text |
| framework-main/arcane/ceapart/src/arcane/geometric/GeneratedGeomElementView.h |all |   ISO-8859 text |
| framework-main/arcane/ceapart/src/arcane/geometric/GeneratedGeomElement.h |all |   ISO-8859 text |
| framework-main/arcane/ceapart/src/arcane/geometric/GeneratedGeomShapeView.h |all |  ISO-8859 text |
| framework-main/arcane/ceapart/src/arcane/geometric/GeneratedConnectivity.h |all |  ISO-8859 text |
| framework-main/arcane/tutorial/microhydro/TypesMicroHydro.h |all |  ISO-8859 text |
| framework-main/arcane/extras/Simd/bench/Wrapper.h |all |  ISO-8859 text |
| framework-main/arcane/extras/Simd/bench/AlignedAllocator.h |all |  ISO-8859 text |
| framework-main/arcane/extras/Simd/arcane_core_config.h |all | ISO-8859 text |
| framework-main/arcane/extras/Simd/arcane/utils/ArrayView.h |all |  ISO-8859 text |
| framework-main/arcane/extras/Simd/arcane/utils/Math.h |all |  ISO-8859 text |
| framework-main/arcane/extras/NumericalModel/src/Utils/ItemVector.h.old |all |  ISO-8859 text |
| framework-main/arcane/extras/NumericalModel/src/Utils/ItemGroupMap.h.old |all |  ISO-8859 text |
| framework-main/arcane/src/arcane/geometry/impl/GeometryServiceBase.cc | all | very long lines |
| framework-main/arcane/extras/NumericalModel/src/Mesh/Geometry/Impl/GeometryServiceBase.cc | all | very long lines |
| framework-main/axlstar/src/client_include/ServiceOptions.h | all |  very long lines |
| framework-main/arcane/src/arcane/core/ServiceOptions.h | all | very long lines |
| framework-main/arcane/src/arcane/utils/StackTrace.cc | all |empty file |
| framework-main/arcane/src/arcane/mesh/CompactIncrementalItemConnectivity.cc | all | empty file |
| framework-main/arcane/src/arcane/geometry/impl/SharedPtrT.h | all |  empty file |
| framework-main/arcane/src/arcane/geometry/ItemGroupMap.h | all |  empty file |
| framework-main/arcane/src/arcane/geometry/IGeometryService.h | all |  empty file |
| framework-main/arcane/src/arcane/utils/Vector.h | all |  empty file |
| framework-main/arcane/src/arcane/core/Factory.h | all |  empty file |
| framework-main/arcane/src/arcane/core/ServiceFinder.h | all |  empty file |
| framework-main/arcane/src/arcane/core/IVariableAccessor.h | all |  empty file |
| framework-main/arcane/src/arcane/core/IPostProcessorReader.h | all |  empty file |
| framework-main/arcane/src/arcane/core/VariableMultiArray2.h | all |  empty file |
| framework-main/arcane/src/arcane/core/VariableAccessor.h | all |  empty file |
| framework-main/arcane/src/arcane/aleph/tests/AlephIndexTest.h | all | empty file |

**Comment by roottreej** [comment]
@AlexlHer, I can not choose an assignee or a label, can you do this please ?

**Comment by grospelliergilles** [comment]
Thanks @roottreej.
We will fix the errors.
For the empty header files, there are here for compatibility reasons so we can not yet remove them.

**Comment by roottreej** [comment]
No problem, I can understand some necessary developer's reasons.
