### ISSUE TITLE
UnifiedMemoryCudaMemoryAllocator::_applyHint when HostAndDeviceMostlyRead

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#753]
In the case where `hint == eMemoryLocationHint::HostAndDeviceMostlyRead`, I don't understand why there are two ifs.

In this case, is it correct to call both:
```
  ARCANE_CHECK_CUDA(cudaMemAdvise(p, new_size, cudaMemAdviseSetPreferredLocation, 0));
  ARCANE_CHECK_CUDA(cudaMemAdvise(p, new_size, cudaMemAdviseSetAccessedBy, cudaCpuDeviceId));
```
AND
```
  ARCANE_CHECK_CUDA(cudaMemAdvise(p, new_size, cudaMemAdviseSetReadMostly, 0));
```

The last one is not sufficient? 
Is it a bug?

**Comment by grospelliergilles** [comment]
It is not a bug but I do not really know if it is useful. I think with only one GPU it is not needed but if you have several GPU it may prevents allocating the memory on all the GPUs. But I am not sure if this is really the case.

For questions, it may be better to use the `Discussions` tab: https://github.com/arcaneframework/framework/discussions
