### ISSUE TITLE
Arcane does not compile with glibc >= 2.34 (Ubuntu 21.10)

### ISSUE THREAD

**Issue by cedricchevalier19** [arcaneframework/framework#77]
`__malloc_hook`s have been deprecated for a long time and are now not explicitly available in `malloc.h`.

https://github.com/arcaneframework/framework/blob/45953e98fecaa4f82fe7124277dcf18d8760bfc5/arcane/src/arcane/utils/MemoryInfo.cc#L128

From glibc 2.34 [changelog](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html):

> * The deprecated memory allocation hooks __malloc_hook, __realloc_hook,
>  __memalign_hook and __free_hook are now removed from the API.  Compatibility
>  symbols are present to support legacy programs but new applications can no
>  longer link to these symbols.  These hooks no longer have any effect on glibc
>  functionality.  The malloc debugging DSO libc_malloc_debug.so currently
>  supports hooks and can be preloaded to get this functionality back for older
>  programs.  However this is a transitional measure and may be removed in a
>  future release of the GNU C Library.  Users may port away from these hooks by
>  writing and preloading their own malloc interposition library.

**Comment by grospelliergilles** [comment]
Thanks.
I will add a test to disable compilation of this file if there are not available.

**Comment by cedricchevalier19** [comment]
Thanks!
