### ISSUE TITLE
Asynchronous `copy` for variables

### ISSUE THREAD

**Issue by DavidDureau** [arcaneframework/framework#938]
Like the issue https://github.com/arcaneframework/framework/issues/936 , we would like to asynchronously copy variables into other variables.

Sequence of copies executed in serial on CPU :
```c++
VariableCellReal var_c1in(...);
VariableCellReal var_c1out(...);
VariableCellReal3 var_c2in(...);
VariableCellReal3 var_c2out(...);

var_c1out.copy(var_c1in);
var_c2out.copy(var_c2in);
```

We would like asynchronous copies on GPU (with a minimal number of kernels) :
```c++
Ref<RunQueue> async_queue = makeQueueRef(...->defaultRunner());
async_queue->setAsync(true);

asyncCopy<Cell>(async_queue, {var_c1out, var_c1in}, {var_c2out, var_c2in});

// ... Some others asynchronous commands on async_queue

async_queue->barrier();
```

**Comment by grospelliergilles** [comment]
Done in #962. The implementation use functions provided by the accelerator runtime (`cudaMemcpyAsync` or `hipMemcpyAsync`):

```
VariableCellReal v1;
VariableCellReal v2;
RunQueue queue;
v1.copy(v2,&queue);
```
If `queue.isAsync()` is true, the copy is asynchronous.

**Comment by DavidDureau** [comment]
Cool, I didn't know it was already possible to asynchronous copy one variable into another one.

Is it possible to fuse several asynchronous copies depending on the item types?

**Comment by grospelliergilles** [comment]
There is no high level function for that. At the moment you have to do something like that:

```
VariableCellReal v1;
VariableCellReal v2;
VariableNodeReal v3;
VariableNodeReal v4;
VariableCellReal v5;
VariableCellReal v6;
RunQueue queue;
v1.copy(v2,&queue);
v3.copy(v4,&queue);
v5.copy(v6,&queue);
queue.barrier();
```

It does not depend on a the item kind so you can mix different item kind.

I will add a high level utility function to do like you described in your issue.

**Comment by DavidDureau** [comment]
In the previous example, the three copies will occur sequentially on the same stream, I would like to fuse {v1<-v2} and {v5<-v6} inside the same kernel (if it is possible of course).

So, in my mind, the `asyncCopy` is not "just" a high level function but a way to describe a set of copies in order to minimize the number of kernel launches and other overheads.

**Comment by grospelliergilles** [comment]
Each copy is not really a kernel but a `cudaMemcpyAsync` so there is no need to fuse them and it should be faster than launching a kernel.

**Comment by DavidDureau** [comment]
OK I see.

And for a `MaterialVariableCellReal`, do you use several calls to `cudaMemcpyAsync`?

**Comment by grospelliergilles** [comment]
It is not implemented a the moment but yes I think it will be like you tell.
