### ISSUE TITLE
Alien Ubuntu 22.04 configure fail

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#940]
The message is 
CMake Error in arcane/src/arcane/dotnet/coreclr/CMakeLists.txt:
  Imported target "arcconpkg_CoreClrEmbed" includes non-existent path

    "/usr/lib/dotnet/packs/Microsoft.NETCore.App.Host.ubuntu.22.04-x64/7.0.10/runtimes/ubuntu.22.04-x64/native"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

The path 
"/usr/lib/dotnet/packs/Microsoft.NETCore.App.Host.ubuntu.22.04-x64/7.0.10/runtimes/ubuntu.22.04-x64/native"
does not exists but path
"/usr/lib/dotnet/packs/Microsoft.NETCore.App.Host.ubuntu.22.04-x64/7.0.12/runtimes/ubuntu.22.04-x64/native"
exists

**Comment by AlexlHer** [comment]
Hi, to fix this error, you can delete the CMakeCache.txt file in your build directory and reconfigure with CMake.

**Comment by grospelliergilles** [comment]
This problem occurs because you have updated your system. The solution provided by @AlexlHer should work. If not, reconfigure and rebuild from an empty directory.
