### ISSUE TITLE
no "all" option for ARCANEFRAMEWORK_BUILD_COMPONENTS

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#949]
Hello,
There is no "all" option for ARCANEFRAMEWORK_BUILD_COMPONENTS. The default is Arcane+Alien so other component are not built.

Also keeping FRAMEWORK_BUILD_COMPONENT in main CMakeList.txt is misleading.

**Comment by grospelliergilles** [comment]
Hi @guignont. The variable `FRAMEWORK_BUILD_COMPONENT` is kept for compatibility with current build system but you are right it should be removed in the future.

For `ARCANEFRAMEWORK_BUILD_COMPONENTS`, it also compile the dependencies. So if you specify `Arcane`, it also compile `Arccore`,  `Arccon`, ... The default is to compile everything (Arcane, Alien, Arccore, ...)
