### ISSUE TITLE
tests fail with "Invalid value. Impossible to convert the string '0.0' to the type 'real'."

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#969]
Hello,
The following tests (ifpen gimkl2018b toolchain) fail with:

Message: Input data are invalid:
 
TraceFile: /work/guignont/work/ArcaneV3/framework/arcane/src/arcane/core/CaseOptionSimple.cc:405
TraceFunc: void Arcane::CaseOptionSimpleT<T>::_search(bool) [with T = double]
<//cas/arcane-post-traitement/frequence-sortie> : Invalid value. Impossible to convert the string '0.0' to the type 'real'.

mesh_modification1_cs_mono
mesh_modification1_cs_mono_embedded
mesh_modification2_cs
hydro_cs_4proc_mono
hydro_cs_4proc_mono_embedded
hydro_cs_mono
hydro_cs_mono_embedded
hydro_cs_task_mono
hydro_cs_task_mono_embedded
casefunction_cs1_mono
casefunction_cs1_mono_embedded
casefunction_cs2_mono
casefunction_cs2_mono_embedded
task2_cs_mono
task2_cs_mono_embedded

**Comment by grospelliergilles** [comment]
I think the problem is because of your locale settings. If the environment variable `LC_NUMERIC` is set to `fr` for example, then the delimiter for floating point is `,` and not `.`. If you set this variable to `C`, it should work.

Even if `LC_NUMERIC` is not set, other variables (for example `LANG`) may change the default delimiter so you have to set `LC_NUMERIC=C` to make sure it overrides the other variables.

**Comment by grospelliergilles** [comment]
Yes. I will force the value of this environment variable in the tests.

**Comment by guignont** [comment]
This is mono that comes with IFPEN gimkl2018b toolchain: Mono/5.10.0.160

**Comment by grospelliergilles** [comment]
Thanks @guignont. I will use this docker file to check. Can you send me the output of the command `locale` to see which values I need to set to reproduce the problem ?

**Comment by guignont** [comment]
Hello,
Sorry for the late response.
Her is the locale output:

LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
