### ISSUE TITLE
[alien,arcane-interface]  ArcaneInterface undefined symbols for Trilinos (MueLu,Tpetra,Xpetra....) package on ubuntu 22.04

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#976]
Hello,
There is undefined symbols when building ArcaneInterface Trilinos module:
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::ParameterListInterpreter<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::ParameterListInterpreter(Teuchos::ParameterList&, Teuchos::RCP<Teuchos::Comm<int> const>, Teuchos::RCP<MueLu::FactoryFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >, Teuchos::RCP<MueLu::FacadeClassFactory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::TpetraOperator<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getRangeMap() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::CrsMatrix(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, Tpetra::ProfileType, Teuchos::RCP<Teuchos::ParameterList> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::print(std::ostream&) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Import(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::putScalar(double const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getComm() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::update(double const&, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, double const&, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, double const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Map(unsigned long, unsigned long, int, Teuchos::RCP<Teuchos::Comm<int> const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::describe(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, Teuchos::EVerbosityLevel) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Xpetra::TpetraMultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraMultiVector(Teuchos::RCP<Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::MLParameterListInterpreter<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MLParameterListInterpreter(Teuchos::ParameterList&, Teuchos::RCP<Teuchos::Comm<int> const>, std::vector<Teuchos::RCP<MueLu::FactoryBase>, std::allocator<Teuchos::RCP<MueLu::FactoryBase> > >) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Xpetra::TpetraCrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraCrsMatrix(Teuchos::RCP<Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::norm2() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::fillComplete(Teuchos::RCP<Teuchos::ParameterList> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isContiguous() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::sync_host() »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Map(unsigned long, Teuchos::ArrayView<int const> const&, int, Teuchos::RCP<Teuchos::Comm<int> const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::subView(Teuchos::Range1D const&) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::fillComplete(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, Teuchos::RCP<Teuchos::ParameterList> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumVectors() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getVector(unsigned long) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::subView(Teuchos::ArrayView<unsigned long const> const&) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::norm1() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::TpetraOperator<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::hasTransposeApply() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::modify_host() »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Ifpack2::Details::Factory<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<Tpetra::RowMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNodeElementList() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::TpetraOperator<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::apply(Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Teuchos::ETransp, double, double) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::get1dCopy(Teuchos::ArrayView<double> const&, unsigned long) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::dot(Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Vector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Vector(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, bool) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalLength() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::replaceGlobalValues(int, Teuchos::ArrayView<int const> const&, Teuchos::ArrayView<double const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::MultiVector(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, bool) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> Tpetra::createOneToOne<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::assign(Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::CrsMatrix(Teuchos::RCP<Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const> const&, unsigned long, Tpetra::ProfileType, Teuchos::RCP<Teuchos::ParameterList> const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::randomize() »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Xpetra::CrsMatrixWrap<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::CrsMatrixWrap(Teuchos::RCP<Xpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getDataNonConst(unsigned long) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalLength() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::HierarchyUtils<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::AddNonSerializableDataToHierarchy(MueLu::HierarchyManager<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&, Teuchos::ParameterList const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalViewHost() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Xpetra::TpetraBlockCrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::TpetraBlockCrsMatrix(Teuchos::RCP<Tpetra::BlockCrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > const&) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Details::Transfer<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::describe(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, Teuchos::EVerbosityLevel) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalElement(int) const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::Hierarchy<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::GetLevel(int) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « MueLu::TpetraOperator<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getDomainMap() const »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::DistObject<char, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doImport(Tpetra::SrcDistObject const&, Tpetra::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode, bool) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::CrsMatrix<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::insertGlobalValues(int, int, double const*, int const*) »
/usr/bin/ld : ../../../lib/libalien_trilinos.so : référence indéfinie vers « Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::subViewNonConst(Teuchos::ArrayView<unsigned long const> const&) »

This is because "global_ordinal_type" template parameter is "int" while ubuntu installed libraries use "long long"
exemple:
> nm -C -D /usr/lib/x86_64-linux-gnu/libtrilinos_muelu-interface.so | grep MueLu::ParameterListInterpreter
0000000000103860 T MueLu::ParameterListInterpreter<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::SetParameterList(Teuchos::ParameterList const&)
0000000000106f60 T MueLu::ParameterListInterpreter<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::SetEasyParameterList(Teuchos::ParameterList const&)
0000000000132c20 T MueLu::ParameterListInterpreter<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::SetFactoryParameterList(Teuchos::ParameterList const&)
0000000000104be0 T MueLu::ParameterListInterpreter<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::ParameterListInterpreter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator
.....

Did anyone experiences this problem ?

**Comment by grospelliergilles** [comment]
No sorry. I have never compiled `Alien/ArcaneInterface` with Trilinos enabled. I have trilinos installed and `Alien` seems to find it (it is displayed in the configuration) but the trilinos module is not compiled. I think it is because of the test `if (TARGET trilinos)` which is never true because there is no `trilinos` target defined in `TrilinosConfig.cmake`.
