### ISSUE TITLE
[arcane] arcane/cmake/Modules/FindTrilinos.cmake with TRILINOS_ROOT

### ISSUE THREAD

**Issue by guignont** [arcaneframework/framework#977]
Hello,
Search path for Trilinos in "arcane/cmake/Modules/FindTrilinos.cmake" cannot be override with TRILINOS_ROOT.

Complementary question: how to override search path for Trilinos in arcane/cmake/Modules/FindTrilinos.cmake ?

A+
Thomas

**Comment by grospelliergilles** [comment]
Hello.
This module file doesn't really search for Trilinos. It search for some components of Trilinos (`AztecOO`, `ML`, `Ifpack` and `Belos`). So you can use `AztecOO_ROOT`, `ML_ROOT`, ... to set the search path.

This package is only used in Arcane for Aleph so I can rename it if it conflicts with your configuration.
